### ISSUE TITLE
Sideloaded apps misinterpreted as system apps 

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#11]
I have several apps which I have either sideloaded or restored by root (app and app data) with oandbackup which are misrepresented as system apps by SDKMonitor.  

Not sure what additional data I can provide to help you, app/package names likely wouldn't help. 

Related: #5

**Comment by bernaferrari** [comment]
So.. This is complicated. I considered system app anything that wasn't installed from play store and anything that wasn't installed manually (by package installer). If I consider anything that has a known origin, there system apps that will be shown, because in my scenario a lot of Samsung apps have a known origin, Samsung installed them.

If you really want, I can change the algorithm to anything that has known origin, but be aware bloat or system apps will appear too.

**Comment by Madis0** [comment]
Are you sure you are not mixing _system_  apps with _pre-installed_  apps in your thought? Even if there are apps that can not be uninstalled or disabled, they aren't _system_  unless defined as so (different partition, I guess?). 

In other words, yes, go for it.

**Comment by bernaferrari** [comment]
Fixed on last version (was already fixed a few weeks ago, but since I never generated an apk for that version..)!

**Comment by Madis0** [comment]
The latest update seemed to slightly increase the number of apps shown, but it still isn't correct, even after clearing SDKMonitor's app data.

SDKMonitor claims I have 117 user apps, AppChecker claims I have 153.

**Comment by bernaferrari** [comment]
This is weird. I’m literally checking if app has a known origin: https://github.com/bernaferrari/SDKMonitor/blob/4ee05b0a21c7ef38bcc8f0ffceb2eeb3ead9ab9c/app/src/main/java/com/bernaferrari/sdkmonitor/core/AppManager.kt#L41
Any idea on how to find the other apps?

**Comment by Madis0** [comment]
SDMaid - 153
OpenAPK [(source)](https://github.com/dkanada/OpenAPK) - 154 

The latter is open source, so it might help.

**Comment by bernaferrari** [comment]
Technically I should never look at gpl code because I'm using Apache 2, unless @dkanada allows.. But I found he is using PackageManager.GET_META_DATA instead of 0 I was using and that returns a few more results - probably what you want.

**Comment by Madis0** [comment]
One line of code, a different language, a system API call... I don't think they'd mind if you implemented that 😄

**Comment by bernaferrari** [comment]
Is it OK now?

**Comment by Madis0** [comment]
Not as of the #9 latest APK. Unless you made a new one?

**Comment by bernaferrari** [comment]
No.. So, could you please clean up data, open it, wait for sync to finish, and send me the logs?

**Comment by Madis0** [comment]
Sent. Seems like all oandbackup and ADB-installed packages have the source `null`, so it's not the best value to check for.

**Comment by bernaferrari** [comment]
> Sent. Seems like all oandbackup and ADB-installed packages have the source null, so it's not the best value to check for.

Uh oh! I just changed completely from that! Reinstall is not necessary, but clean data is:
http://s000.tinyupload.com/index.php?file_id=48822454369088013120

**Comment by Madis0** [comment]
It is now correct! 🎉

**Comment by bernaferrari** [comment]
Thanks!
